# name: Datadog CI Installation

# on:
#   pull_request:
#     branches:
#       - main

# jobs:
#   install-datadog-ci:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install Datadog CI
#         run: npm install -g @datadog/datadog-ci

#       - name: Configure Datadog keys
#         run: |
#           echo "DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }}" >> $GITHUB_ENV
#           echo "DATADOG_APP_KEY=${{ secrets.DATADOG_APP_KEY }}" >> $GITHUB_ENV

#       - name: Verify Datadog CI Installation
#         run: datadog-ci --version
name: Datadog PR Event

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  push-event-to-datadog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Datadog CI
        run: npm install -g @datadog/datadog-ci

      - name: Configure Datadog keys
        run: |
          echo "DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }}" >> $GITHUB_ENV
          echo "DATADOG_APP_KEY=${{ secrets.DATADOG_APP_KEY }}" >> $GITHUB_ENV
          echo "DD_BETA_COMMANDS_ENABLED=1" >> $GITHUB_ENV 
          echo "DD_SITE=${{ secrets.DD_SITE }}" >> $GITHUB_ENV

      - name: Push deployment event to Datadog
        run: |
          deploy_start=$(date +%s)
          datadog-ci dora deployment --service shopist --env prod --started-at $deploy_start --finished-at $(date +%s)

