name: Deploy and Report to Datadog

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        export DD_BETA_COMMANDS_ENABLED=1
        export DD_SITE="https://app.datadoghq.com" # Replace with your Datadog site (e.g., datadoghq.com or datadoghq.eu)
        export DD_API_KEY="${{ secrets.DATADOG_API_KEY }}"

    - name: Start Deployment Timer
      id: deploy_start
      run: echo "deploy_start=$(date +%s)" >> $GITHUB_ENV

    - name: Deploy Application
      run: |
        ./your-deploy-script.sh

    - name: Report Deployment to Datadog
      run: |
        datadog-ci dora deployment --service eztravel --env production \
          --started-at ${{ env.deploy_start }} --finished-at $(date +%s) \
          --git-repository-url "https://github.com/quresmu/eztravel" \
          --git-commit-sha ${{ github.event.pull_request.head.sha }}
      env:
        DD_BETA_COMMANDS_ENABLED: 1
        DD_SITE: "https://app.datadoghq.com"
        DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
